# ------------------
#  Website Metadata
# ------------------
title: Serenade Wind
email: serenadewind@gmail.com
locale: "en-US"
ampdir: amp
description: Follow us as we embark on this new journey from quitting our corporate jobs and buying a boat to downsizing our possessions in order to begin our sailing adventure around the world. 
url: 'https://serenadewind.com'
background_image: "serenade-wind-background"
# -------------------
#   SEO and Social
# -------------------
social:
  name: Serenade Wind
  links:
    - https://twitter.com/serenade_wind
    - https://www.facebook.com/serenade.wind.adventures
    - https://www.instagram.com/serenade.wind
    - https://reddit.com/user/serenade_wind
facebook:
  publisher: https://www.facebook.com/serenade.wind.ventures
# -------------------
#  Settings
# -------------------
markdown: kramdown
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/dark.css"
read_time: true
words_per_minute: 200
google_fonts:
  - name: "Princess Sofia"
    weights: "400,500,600"
  - name: "Montez"
  - name: "Poiret One"
    weights: "400,500,600"
google_analytics: UA-157589130-1
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-include-cache
exclude: 
  - jekyll-image-gallery-example
  - node_modules
  - tools
  - image-resize.py
  - image-file-undo.py
  - package.json
  - Gemfile
  - Gemfile.lock
  # - _drafts
  - .jekyll-cache
  - _backlog
include:
  - _redirects #netfly redirect
  - _headers